force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountHandler.cls
public with sharing class AccountHandler {
    public static void PreventDeletion(List<Account> Accounts) {
        Set<String> AccountId = new Set<String>();
            for(Account acc: Accounts) {    
                AccountId.add(acc.ID);
            }
        List<Policy__c> policyDet = [SELECT Account__c FROM Policy__c WHERE Account__c IN :AccountId and Policy_Status__c = 'Active'];
    
        //checking policy
        Set<String> PolicyaccId = new Set<String>();
        for (Policy__C policy : policyDet) {
            PolicyaccId.add(policy.Account__c);
        }
    
        for(Account AccDet: Accounts){
            if(PolicyaccId.contains(AccDet.Id)) 
                AccDet.addError('Account has an Active policy');        
        }
    }

    public static void PreventDuplicatePhone(List<Account> Accounts) {
        Set<String> setPhone = new Set<String>();
        for (Account acc: Accounts) {
            setPhone.add(acc.Phone);
        }
        setPhone.remove(null);

        if(setPhone.size() > 0) {
            List<Account> listAccount = [SELECT Phone, id FROM Account WHERE Phone IN :setPhone];
            Map<String, Account> mapPhoneVsAccount = new Map<String, Account>();
            for(Account acc: listAccount) {
                mapPhoneVsAccount.put(acc.Phone, acc);
            }

            for(Account acc: Accounts) {
                if(mapPhoneVsAccount.containsKey(acc.Phone)) {
                    acc.addError('Duplicate! Phone number exists already!');
                }
            }
        }
    }
}