force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/ProductP__c.field-meta.xml
<CustomField>
    <fullName>ProductP__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N665</fullName>
            </value>
            <value>
                <fullName>19F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PolicyController.cls
public class PolicyController {
    
    public List<Policy__c> Policies {get; set;}
    public List<Policy__c> filteredList {get; set;}
    public String filter {get; set;}
    public Id polId {get; set;}
    
    public PolicyController() {
        
        filter = null;
        polId = null;
        
        List<Policy__c> allPols = [SELECT Id, Name, Account__r.Name, ProductP__c FROM Policy__c];
        Policies = new List<Policy__c>();
        filteredList = new List<Policy__c>();

        for(Policy__c currPol : allPols){
            Policies.add(currPol);
            filteredList.add(currPol);
        }
    }
    
    public PageReference NextPage() {
        System.debug('NextPage()' + polId);
        polId = Apexpages.currentpage().getParameters().get('polId');
        System.debug('NextPage()' + polId);
        return Page.PoliciesPage2;
    }
    
    public PageReference PrevPage() {
        System.debug('PrevPage()' + polId);
        return Page.PoliciesPage;
    }
    
    public void FilterList(){
        filteredList = new List<Policy__c>();
        for(Policy__c currPol : Policies){
            String lowercasePol = currPol.Name.toLowerCase();
            if(lowercasePol.Contains(filter)){ 
                filteredList.add(currPol);
            }
        }
    }
}