force-app/main/default/objects/Order/fields/Order_Cost__c.field-meta.xml
<CustomField>
    <fullName>Order_Cost__c</fullName>
    <label>Order Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity__c</fullName>
    <label>Order Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Product_InterestOrder__c.field-meta.xml
<CustomField>
    <fullName>Product_InterestOrder__c</fullName>
    <label>Product Interest</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N665</fullName>
            </value>
            <value>
                <fullName>19F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Cost__c.field-meta.xml
<CustomField>
    <fullName>Policy_Cost__c</fullName>
    <label>Policy Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Owner1__c.field-meta.xml
<CustomField>
    <fullName>Policy_Owner1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Owner_Phone__c.field-meta.xml
<CustomField>
    <fullName>Policy_Owner_Phone__c</fullName>
    <label>Policy Owner Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Policy_Quantity__c</fullName>
    <label>Policy Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/ProductP__c.field-meta.xml
<CustomField>
    <fullName>ProductP__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N665</fullName>
            </value>
            <value>
                <fullName>19F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataFactory.cls
/*
    Created By: Kevin Neisser & Jonathan Thomas
    Last Updated: 5/10/2022 
    Description: Factory for order test class. Generates contacts, accounts and orders
*/

public class DataFactory {
    
    public static List<Contact> generateContacts(Integer numContacts){
        List<Contact> ConsForTest = new List<Contact>();
        for (Integer i = 0; i < numContacts; i++){
            Contact newContact = new Contact(LastName = 'TestName' + i, Phone = '1112223333');
            ConsForTest.add(newContact);
        }
        return ConsForTest;
    }
    
    public static List<Account> generateAccounts(Integer numAcc){
        List<Account> AccsForTest = new List<Account>();
        for(Integer i = 0; i < numAcc; i++){
            Account newAccount = new Account(Name = 'Test' + i);
            AccsForTest.add(newAccount);
        }
        return AccsForTest;
    }
    
    public static List<Order> generateOrders(Account acc, Contact con, Integer numOrder){
        List<Order> OrderForTest = new List<Order>();
        
        for(Integer i = 0; i < numOrder; i++){
            Order newOrder = new Order(AccountId = acc.Id, 
                                EffectiveDate = Date.newInstance(2022, 06, 01), 
                                Product_InterestOrder__c ='19F', 
                                Order_Quantity__c =1, 
                                Order_Cost__c =20001, 
                                Status ='Draft', 
                                CustomerAuthorizedById = con.Id);
            
            OrderForTest.add(newOrder);
        }
        return OrderForTest;       
    }
    
    public static List<Policy__c> generatePolicies(Account acc, Contact con, Integer numPolicy){
        List<Policy__c> PolicyForTest = new List<Policy__c>();
        
        for(Integer i = 0; i < numPolicy; i++){
            Policy__c newPolicy = new Policy__c(Account__c = acc.Id,
                                                Policy_Owner1__c = con.Id,
                                                //Order__c = testOrders[1].Id,
                                                Policy_Owner_Phone__c = con.Phone,
                                                Policy_Cost__c = 1000,
                                                Policy_Status__c = 'active',
                                                ProductP__c = '19F', 
                                                Policy_Quantity__c = 1);
            
           PolicyForTest.add(newPolicy);
        }
        return PolicyForTest;       
    }
}